 # ISYS2407 Information Systems Solutions & Design

# Assignment 3

# Feature Selection

#### Student name: Muhammad Ali Syed

#### Student number: s3640387

# Import libraries 

In [1]:
import pandas as pd
import numpy as np

# Library for splitting the data into train and test sets
from sklearn.model_selection import train_test_split 

# Libraries to select k best features
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

## Load the data set 

In [2]:
passengerSatisfaction_df = pd.read_csv('passenger-satisfaction.csv')  

# Check
passengerSatisfaction_df.head()

id  gender      customer_type  age   type_of_travel     class  \
0   70172    Male     Loyal Customer   13  Personal Travel  Eco Plus   
1    5047    Male  Disloyal Customer   25  Business travel  Business   
2  110028  Female     Loyal Customer   26  Business travel  Business   
3   24026  Female     Loyal Customer   25  Business travel  Business   
4  119299    Male     Loyal Customer   61  Business travel  Business   

   flight_distance  inflight_wifi_service  convenient_departure_arrival_time  \
0              460                      3                                  4   
1              235                      3                                  2   
2             1142                      2                                  2   
3              562                      2                                  5   
4              214                      3                                  3   

   ease_of_online_booking  ...  inflight_entertainment  onboard_service  \
0                       3  ...                       5                4   
1                       3  ...                       1                1   
2                       2  ...                       5                4   
3                       5  ...                       2                2   
4                       3  ...                       3                3   

   leg_room_service  baggage_handling  checkin_service  inflight_service  \
0                 3                 4                4                 5   
1                 5                 3                1                 4   
2                 3                 4                4                 4   
3                 5                 3                1                 4   
4                 4                 4                3                 3   

   cleanliness  departure_delay(mins)  arrival_delay(mins)  satisfaction  
0            5                     25                 18.0             0  
1            1                      1                  6.0             0  
2            5                      0                  0.0             1  
3            2                     11                  9.0             0  
4            3                      0                  0.0             1  

[5 rows x 24 columns]

## Split the data into training and testing sets 

In [3]:
# Features are variables that affect the target/label
# So, it's all the columns excluding the target column
# However, you may also use a subset of features previously identified as best features
# You might want to experiment with both the full set and the best features
feature_cols = [
    'age', 
    'flight_distance', 
    'inflight_wifi_service', 
    'convenient_departure_arrival_time',
    'ease_of_online_booking', 
    'gate_location', 
    'food_and_drink', 
    'online_boarding',
    'seat_comfort',
    'inflight_entertainment',
    'onboard_service',
    'leg_room_service',
    'baggage_handling',
    'checkin_service'
    
]

X = passengerSatisfaction_df[feature_cols]
# print('X:\n', X)

# Store the labels/target in variable y (lower case as its a single value)
y = passengerSatisfaction_df['gender']
# print('y:\n', y)

# Split into train/test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, # keep 30% for testing
                                                    random_state=2) # pass an int for reproducible rtesult)

In [4]:
print(X_train.shape)
print(X_train)


(72732, 14)
        age  flight_distance  inflight_wifi_service  \
58712    24              283                      3   
78436    22             1598                      2   
71500    52             3965                      3   
68106    30             2865                      1   
25689    40              368                      3   
...     ...              ...                    ...   
44566    36              738                      2   
95816    47              406                      2   
72173    51             1120                      3   
100879   58              235                      2   
89256    21              447                      4   

        convenient_departure_arrival_time  ease_of_online_booking  \
58712                                   0                       3   
78436                                   1                       2   
71500                                   4                       2   
68106                                   1          

In [5]:
print(X_test.shape)
print(X_test)

(31172, 14)
        age  flight_distance  inflight_wifi_service  \
18981    49             3417                      4   
4555     19              328                      2   
44022    52              667                      1   
84411    65              997                      4   
91989    31              403                      3   
...     ...              ...                    ...   
2620     50             3477                      5   
21396    44              846                      3   
94078    41             3369                      2   
10550    30              484                      2   
101352   48             1616                      2   

        convenient_departure_arrival_time  ease_of_online_booking  \
18981                                   4                       2   
4555                                    0                       2   
44022                                   4                       1   
84411                                   5          

## Trial and error process 

### Attempt 1 

In [6]:
# k = 7
X_selected = SelectKBest(chi2, k=7).fit_transform(X_train, y_train)

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 5 rows of the selected features
print(X_selected[:5])

# Print the first 5 rows of all the features in the dataset
X_train.head()

<class 'numpy.ndarray'>
(72732, 7)
[[  24  283    3    3    1    5    4]
 [  22 1598    2    2    2    4    4]
 [  52 3965    3    2    3    3    3]
 [  30 2865    1    4    4    3    5]
 [  40  368    3    3    3    2    4]]


age  flight_distance  inflight_wifi_service  \
58712   24              283                      3   
78436   22             1598                      2   
71500   52             3965                      3   
68106   30             2865                      1   
25689   40              368                      3   

       convenient_departure_arrival_time  ease_of_online_booking  \
58712                                  0                       3   
78436                                  1                       2   
71500                                  4                       2   
68106                                  1                       1   
25689                                  3                       3   

       gate_location  food_and_drink  online_boarding  seat_comfort  \
58712              4               1                3             1   
78436              4               2                2             2   
71500              4               5                2             3   
68106              1               4                4             4   
25689              3               3                3             3   

       inflight_entertainment  onboard_service  leg_room_service  \
58712                       1                3                 5   
78436                       2                1                 4   
71500                       3                3                 3   
68106                       4                5                 3   
25689                       3                3                 2   

       baggage_handling  checkin_service  
58712                 4                3  
78436                 4                4  
71500                 3                3  
68106                 5                4  
25689                 4                4

### Attempt 2 

In [7]:
# for k = 5
X_selected = SelectKBest(chi2, k=5).fit_transform(X_train, y_train)

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 5 rows of the selected features
print(X_selected[:5])

# Print the first 5 rows of all the features in the dataset
X_train.head()

<class 'numpy.ndarray'>
(72732, 5)
[[ 283    3    1    5    4]
 [1598    2    2    4    4]
 [3965    2    3    3    3]
 [2865    4    4    3    5]
 [ 368    3    3    2    4]]


age  flight_distance  inflight_wifi_service  \
58712   24              283                      3   
78436   22             1598                      2   
71500   52             3965                      3   
68106   30             2865                      1   
25689   40              368                      3   

       convenient_departure_arrival_time  ease_of_online_booking  \
58712                                  0                       3   
78436                                  1                       2   
71500                                  4                       2   
68106                                  1                       1   
25689                                  3                       3   

       gate_location  food_and_drink  online_boarding  seat_comfort  \
58712              4               1                3             1   
78436              4               2                2             2   
71500              4               5                2             3   
68106              1               4                4             4   
25689              3               3                3             3   

       inflight_entertainment  onboard_service  leg_room_service  \
58712                       1                3                 5   
78436                       2                1                 4   
71500                       3                3                 3   
68106                       4                5                 3   
25689                       3                3                 2   

       baggage_handling  checkin_service  
58712                 4                3  
78436                 4                4  
71500                 3                3  
68106                 5                4  
25689                 4                4

### Attempt 3

In [8]:
# Try k=4
X_selected = SelectKBest(chi2, k=4).fit_transform(X_train, y_train)

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 5 rows of the selected features
print(X_selected[:5])

# Print the first 5 rows of all the features in the dataset
X_train.head()

<class 'numpy.ndarray'>
(72732, 4)
[[ 283    3    5    4]
 [1598    2    4    4]
 [3965    2    3    3]
 [2865    4    3    5]
 [ 368    3    2    4]]


age  flight_distance  inflight_wifi_service  \
58712   24              283                      3   
78436   22             1598                      2   
71500   52             3965                      3   
68106   30             2865                      1   
25689   40              368                      3   

       convenient_departure_arrival_time  ease_of_online_booking  \
58712                                  0                       3   
78436                                  1                       2   
71500                                  4                       2   
68106                                  1                       1   
25689                                  3                       3   

       gate_location  food_and_drink  online_boarding  seat_comfort  \
58712              4               1                3             1   
78436              4               2                2             2   
71500              4               5                2             3   
68106              1               4                4             4   
25689              3               3                3             3   

       inflight_entertainment  onboard_service  leg_room_service  \
58712                       1                3                 5   
78436                       2                1                 4   
71500                       3                3                 3   
68106                       4                5                 3   
25689                       3                3                 2   

       baggage_handling  checkin_service  
58712                 4                3  
78436                 4                4  
71500                 3                3  
68106                 5                4  
25689                 4                4